### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by xin007-kong** [flepied/second-brain-agent#42]
Hello, I'd like to open an issue and was wondering if it would be possible to provide the 'requirements.txt' file to help with setting up the environment. This would greatly assist in configuring the environment correctly. Thank you!

**Comment by fredericlepied** [comment]
Hi @xin007-kong 

Poetry doesn't work for you? What is the issue with poetry?

Fred

**Comment by fredericlepied** [comment]
You can use https://github.com/python-poetry/install.python-poetry.org to install poetry if you don't have it already.

**Comment by flepied** [comment]
No update so closing the issue.
